# frozen_string_literal: true

require_relative "config/application"
require "rake/testtask"

Rails.application.load_tasks
Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList["test/**/*_test.rb"]
end

task(default: :test)
